### ISSUE TITLE
`cos_prereg()` not knitting with bibliography?

### ISSUE THREAD

**Issue by nsunami** [crsh/prereg#16] opened 2020-12-11 12:47 UTC
I'm trying to knit a preregistration file with bibliography with `prereg::cos_prereg()` but failing with an error message:

`! LaTeX Error: Environment CSLReferences undefined.`

I have the following metadata:
```
output: prereg::cos_prereg
bibliography      : "preregistration.bib"
```
If I comment out `output: prereg::cos_prereg()`, the file will knit. I'm guessing this is something to do with Pandoc 2.8 and the .tex template as mentioned [here](https://github.com/rstudio/rmarkdown/issues/1649).

**Comment by crsh** [comment] 2020-12-23 14:35
Hi Nami, thanks for raising this issue. This error is caused by upstream changes in `pandoc`. To address this problem at its root will take a little time, but I have drafted a hot fix for this issue: Could you try installing with `remotes::install_github("crsh/prereg@issue-16")` to see if that fixes the problem?

**Comment by nsunami** [comment] 2021-01-04 13:42
Thank you, Frederik! That fixed the problem, and I was able to knit the document without issues.

**Closed as completed** 2021-11-16 23:13 UTC
Labels: bug
